final_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("final_logs.urls")),
    path("users/", include("users.urls")),
]

final_logs/urls.py
from django.urls import path

from . import views

app_name = "final_logs"

urlpatterns = [
    path("", views.index, name="index"),
    path("pizzas", views.pizzas, name="pizzas"),
    path("pizzas/<int:pizza_id>/", views.pizza, name="pizza"),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

final_logs/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class Pizza(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

final_logs/views.py
from django.shortcuts import render

# Create your views here.

from .models import Pizza, Topping
from django.contrib.auth.decorators import login_required


@login_required
def pizzas(request):
    pizzas = Pizza.objects.order_by("date_added")

    context = {"pizzas": pizzas}

    return render(request, "final_logs/pizzas.html", context)


@login_required
def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    toppings = pizza.topping_set.order_by("-date_added")

    context = {"pizza": pizza, "toppings": toppings}

    return render(request, "final_logs/pizza.html", context)


def index(request):
    """The home page for Final Log. """
    return render(request, "final_logs/index.html")

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def register(request):
    """Register new user"""
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("final_logs:index")

    context = {"form": form}
    return render(request, "registration/register.html", context)

final_logs/templates/final_logs/base.html
<p>

    <body style="background-color: rgb(250, 202, 202)" </body>
        <font face="Optima" size="70px" color="246482"> Blake's Pizza </font><br /><br />
        <a href="{% url 'final_logs:index' %}">Final Log</a>
        <a href="{% url 'final_logs:pizzas' %}">Pizzas</a>
        {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Log Out</a>
        {% else %}
        <a href="{% url 'users:register' %}">Register</a>
        <a href="{% url 'users:login' %}">Log In</a>
        {% endif %}

</p>

{% block content %}{% endblock content %}

final_logs/templates/final_logs/index.html
{% extends "final_logs/base.html" %}

{% block content %}

<head>
    <title>Pizza Final Project WebPage</title>
</head>

{% endblock content %}

final_logs/templates/final_logs/pizza.html
{% extends "final_logs/base.html" %}

{% block content %}

<p>Pizza: {{ pizza }}</p>

<ul>
    {% for topping in toppings %}

    <li>
        <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ topping.text|linebreaks }}</p>
    </li>
    {% empty %}
    <li>There are no toppings for this pizza yet.</li>
    {% endfor %}



</ul>

{% endblock content %}

final_logs/templates/final_logs/pizzas.html
{% extends "final_logs/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}

    <li>
        <a href="{% url 'final_logs:pizza' pizza.id %}">{{ pizza }}</a>
    </li>
    {% empty %}
    <li>No Pizzas have been added yet.</li>
    {% endfor %}



</ul>

{% endblock content %}